//
// Created by Jonathan on 7/19/2017.
//

#ifndef CHESSPROJECT_CONSTANTS_H
#define CHESSPROJECT_CONSTANTS_H

#define MALLOC_ERROR "Error: malloc failed"
#define SUCCESS 0
#define FAIL -1
#define MAX_HISTORY_SIZE 6
#define MAX_COMMAND_LENGTH 1024
#define DEFAULT_GAME_MODE PlayerVsComputer
#define DEFAULT_DIFFICULTY '2'
#define DEFAULT_USER_COLOR White
#define DEFAULT_CURRENT_PLAYER Player1
#define CAN_HANDLE_EXPERT_DIFFICULTY 1
#define CAN_UNDO_IN_2_PLAYER_MODE 0


#endif //CHESSPROJECT_CONSTANTS_H
