#ifndef BMPPATHCONSTANTS_H_
#define BMPPATHCONSTANTS_H_

#define NEW_GAME_BUTTON_MAIN_WINDOW_TEXTURE_PATH "./Gui/images/MainWindow/start.bmp"
#define LOAD_GAME_BUTTON_MAIN_WINDOW_TEXTURE_PATH "./Gui/images/MainWindow/load.bmp"
#define QUIT_GAME_BUTTON_MAIN_WINDOW_TEXTURE_PATH "./Gui/images/MainWindow/quit.bmp"
#define BACKGROUND_MAIN_WINDOW_TEXTURE_PATH "./Gui/images/MainWindow/background.bmp"

#define BACKGROUND_GAME_WINDOW_TEXTURE_PATH "./Gui/images/GameWindow/background.bmp"
#define SAVE_GAME_BUTTON_GAME_WINDOW_TEXTURE_PATH "./Gui/images/GameWindow/save.bmp"
#define LOAD_GAME_BUTTON_GAME_WINDOW_TEXTURE_PATH "./Gui/images/GameWindow/load.bmp"
#define UNDO_BUTTON_GAME_WINDOW_TEXTURE_PATH "./Gui/images/GameWindow/undo.bmp"
#define UNAVAILABLE_UNDO_BUTTON_GAME_WINDOW_TEXTURE_PATH "./Gui/images/GameWindow/unavailable_undo.bmp"
#define GO_TO_MAIN_WINDOW_BUTTON_GAME_WINDOW_TEXTURE_PATH "./Gui/images/GameWindow/go_to_main_window.bmp"
#define RESTART_GAME_BUTTON_GAME_WINDOW_TEXTURE_PATH "./Gui/images/GameWindow/restart.bmp"
#define QUIT_GAME_BUTTON_GAME_WINDOW_TEXTURE_PATH "./Gui/images/GameWindow/quit.bmp"

#define PIECE_TEXTURE_PATH_FORMAT "./Gui/images/GameBoard/piece_%d_%d.bmp"
#define GAME_BOARD_TEXTURE_PATH_FORMAT "./Gui/images/GameBoard/board_%d.bmp"

#define BACKGROUND_GAME_MODE_NEW_GAME_WINDOW_TEXTURE_PATH "./Gui/images/NewGameWindow/background_game_mode.bmp"
#define BACKGROUND_DIFFICULTY_NEW_GAME_WINDOW_TEXTURE_PATH "./Gui/images/NewGameWindow/background_difficulty.bmp"
#define BACKGROUND_USER_COLOR_NEW_GAME_WINDOW_TEXTURE_PATH "./Gui/images/NewGameWindow/background_user_color.bmp"
#define NEXT_NEW_GAME_WINDOW_TEXTURE_PATH "./Gui/images/NewGameWindow/next.bmp"
#define START_NEW_GAME_NEW_GAME_WINDOW_TEXTURE_PATH "./Gui/images/NewGameWindow/start.bmp"
#define WHITE_NEW_GAME_WINDOW_TEXTURE_PATH "./Gui/images/NewGameWindow/white_color.bmp"
#define WHITE_NEW_GAME_WINDOW_PRESSED_TEXTURE_PATH "./Gui/images/NewGameWindow/pressed/white_color.bmp"
#define BLACK_NEW_GAME_WINDOW_TEXTURE_PATH "./Gui/images/NewGameWindow/black_color.bmp"
#define BLACK_NEW_GAME_WINDOW_PRESSED_TEXTURE_PATH "./Gui/images/NewGameWindow/pressed/black_color.bmp"
#define ONE_PLAYER_NEW_GAME_WINDOW_TEXTURE_PATH "./Gui/images/NewGameWindow/one_player_mode.bmp"
#define ONE_PLAYER_NEW_GAME_WINDOW_PRESSED_TEXTURE_PATH "./Gui/images/NewGameWindow/pressed/one_player_mode.bmp"
#define TWO_PLAYER_NEW_GAME_WINDOW_TEXTURE_PATH "./Gui/images/NewGameWindow/two_player_mode.bmp"
#define TWO_PLAYER_NEW_GAME_WINDOW_PRESSED_TEXTURE_PATH "./Gui/images/NewGameWindow/pressed/two_player_mode.bmp"
#define NOOB_NEW_GAME_WINDOW_TEXTURE_PATH "./Gui/images/NewGameWindow/noob_diff.bmp"
#define NOOB_NEW_GAME_WINDOW_PRESSED_TEXTURE_PATH "./Gui/images/NewGameWindow/pressed/noob_diff.bmp"
#define EASY_NEW_GAME_WINDOW_TEXTURE_PATH "./Gui/images/NewGameWindow/easy_diff.bmp"
#define EASY_NEW_GAME_WINDOW_PRESSED_TEXTURE_PATH "./Gui/images/NewGameWindow/pressed/easy_diff.bmp"
#define MODERATE_NEW_GAME_WINDOW_TEXTURE_PATH "./Gui/images/NewGameWindow/moderate_diff.bmp"
#define MODERATE_NEW_GAME_WINDOW_PRESSED_TEXTURE_PATH "./Gui/images/NewGameWindow/pressed/moderate_diff.bmp"
#define HARD_NEW_GAME_WINDOW_TEXTURE_PATH "./Gui/images/NewGameWindow/hard_diff.bmp"
#define HARD_NEW_GAME_WINDOW_PRESSED_TEXTURE_PATH "./Gui/images/NewGameWindow/pressed/hard_diff.bmp"
#define EXPERT_NEW_GAME_WINDOW_TEXTURE_PATH "./Gui/images/NewGameWindow/expert_diff.bmp"
#define EXPERT_NEW_GAME_WINDOW_PRESSED_TEXTURE_PATH "./Gui/images/NewGameWindow/pressed/expert_diff.bmp"
#define BACK_NEW_GAME_WINDOW_TEXTURE_PATH "./Gui/images/NewGameWindow/back.bmp"

#define NUMBER_OF_SAVE_LOAD_SLOT 5
#define LOAD_BUTTON_LOAD_WINDOW_TEXTURE_PATH_FORMAT "./Gui/images/LoadWindow/load.bmp"
#define LOAD_UNAVAILABLE_BUTTON_LOAD_WINDOW_TEXTURE_PATH_FORMAT "./Gui/images/LoadWindow/load_unavailable.bmp"
#define LOAD_SLOT_BUTTON_LOAD_WINDOW_TEXTURE_PATH_FORMAT "./Gui/images/LoadWindow/slot_%d.bmp"
#define LOAD_SLOT_BUTTON_SELECTED_LOAD_WINDOW_TEXTURE_PATH_FORMAT "./Gui/images/LoadWindow/slot_%d_selected.bmp"
#define BACK_BUTTON_LOAD_WINDOW_TEXTURE_PATH "./Gui/images/LoadWindow/back.bmp"
#define BACKGROUND_LOAD_WINDOW_TEXTURE_PATH "./Gui/images/LoadWindow/background.bmp"
#define SAVE_LOAD_PATH_FORMAT "./save_slot_%d.xml"

#endif
